---
### Mysql Default Settings

# Hide passwords from logs
mysql_hide_passwords: true

# STIG Manager database name, this is a required variable
mysql_database_name: stigman

# STIG Manager database user, this is a required variable
mysql_user_name: stigman

# STIG Manager database user password, this is a required variable
mysql_user_password: 'MySecurePassword'

# MySQL database root user, this is a required variable
mysql_root_username: root

# MySQL database root password, this is a required variable
mysql_root_pass: ""

# RHEL MySQL Data Directory to use
mysql_data_dir: /var/lib/mysql

#
mysql_default_data_dir: /var/lib/mysql

#
mysql_mycnf: /etc/my.cnf

## Mysql configuration settings
# Sets the amount of memory for a buffer that is allocated for sessions performing a sort.
mysql_sort_buffer_size: 64M

# Sets the amount of memory to use to cache tables, indexes and a few other things.
mysql_innodb_buffer_pool_size: 2G


# Client
mysql_client_port: 3306 
mysql_client_cnf: /etc/my.cnf.d/client.cnf
mysql_server_cnf: /etc/my.cnf.d/mysql-server.cnf
