---
- name: "Start {{ keycloak.service_name }} service"
  ansible.builtin.systemd:
    name: keycloak
    enabled: true
    state: started
    daemon_reload: true
  become: true
  tags:
    - keycloak

- name: "Wait until {{ keycloak.service_name }} becomes active {{ keycloak.health_url }}"
  ansible.builtin.uri:
    url: "{{ keycloak.health_url }}"
  register: keycloak_status
  until: keycloak_status.status == 200
  retries: 25
  delay: 10
  tags:
    - keycloak
