---
### STIG Manager Watcher

## Manual download
# curl -OL https://github.com/NUWCDIVNPT/stigman-watcher/releases/download/1.4.6/stigman-watcher-linux-1.4.6.tar.gz

## Configuration specific to stigman watcher
watcher_pkg: tar.gz
watcher_version: 1.4.6
watcher_archive: "stigman-watcher-linux-{{ watcher_version }}.{{ watcher_pkg }}"
watcher_download_url: "https://github.com/NUWCDIVNPT/stigman-watcher/releases/download/{{ watcher_version }}/{{ watcher_archive }}"
watcher_installdir: "{{ watcher_dest }}/stigman-watcher-{{ watcher_version }}"

# whether to install from local archive
watcher_offline_install: "{{ offline_install | default(true) | bool }}"

# Athentication strategy
watcher_auth_strategy: client_id

### Install location and service settings
watcher_dest: /opt
watcher_home: "{{ watcher_installdir }}"
watcher_symlink: /opt/stigman-watcher
watcher_service_user: stigman
watcher_service_group: stigman
watcher_service_restart_always: true
watcher_service_restart_on_failure: true
watcher_service_restartsec: "60s"
watcher_config_file: "{{ watcher_home }}/.env"

watcher_hostname: "{{ ansible_hostname | d('localhost') }}"
watcher_http_port: 8080
watcher_force_health_check: true  #deprecated 
watcher_health_check_enabled: true

### Using Default Configuration
watcher_add_existing: true
watcher_api_base: http://localhost:54000/api
watcher_authority: http://localhost:8080/realms/stigman
watcher_cargo_delay: 2000
watcher_cargo_size: 25

## Authentication using client_id
watcher_client_id: stigman-watcher
watcher_client_secret: 954fd71a-dad6-47ab-8035-060268f3d396

# Authentication using client_key
watcher_client_key: 
watcher_client_key_passphrase: 

watcher_collection: 1
watcher_create_objects: true
watcher_ignore_globs: "**/ignoredDir,**/someDir/ignoredFile"
watcher_log_file: "logs/watcher.log"
watcher_log_file_level: debug
watcher_history_file: "logs/history.log"
watcher_log_level: info

#
watcher_path: "/opt/windows"

#
watcher_use_polling: false
watcher_stability_threshold: 5000
watcher_mode: scan
watcher_scan_interval: 60000



# http://localhost:54000/api/api/op/definition