---
- name: Restart and enable service
  ansible.builtin.systemd:
    name: "{{ stigman.service_name }}"
    enabled: true
    state: restarted
    daemon_reload: true
  become: true
  tags:
    - always

- name: Wait until service becomes active
  ansible.builtin.uri:
    url: "{{ stigman.health_url }}"
  register: stigman_status
  until: stigman_status.status == 200
  retries: "{{ stigman_restart_health_check_reries | default(5) }}"
  delay: "{{ stigman_restart_health_check_delay | default(3) }}"
  when: stigman_force_health_check | default(true)
  tags:
    - always
