---
- name: "Configure systemd unit file for stigman service"
  ansible.builtin.template:
    src: stigman.service.j2
    dest: /etc/systemd/system/stigman.service
    owner: root
    group: root
    mode: '0644'
  become: true
  register: systemdunit
  tags:
    - always

- name: "Configure sysconfig file for {{ stigman.service_name }} service"
  become: true
  ansible.builtin.template:
    src: stig-manager.sh.j2
    dest: "{{ stigman_config_file }}"
    owner: stigman
    group: stigman
    mode: '0755'
  notify:
    - restart stigman
  tags:
    - always