---
# https://www.continuent.com/resources/blog/automated-mysql-server-preparation-using-ansible
- name: Start GSC STIG-Manager Intallation Playbook
  hosts: stigman
  become: yes
  become_method: sudo

  tasks:
    - name: Install MySQL packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
      vars:
         packages:
           - mysql-server
           - python3-PyMySQL
 
    - name: Enable the MySQL service
      service:
        name: mysqld
        state: started
        enabled: true

    - name: Acquire temporary root password
      shell: "awk -F': ' '$0 ~ \"temporary password\"{print $2}' /var/log/mysqld/mysqld.log"
      register: mysql_root_password_temp

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: mysql_root_password_temp
        verbosity: 2

    - name: Set new root password from default temporary password
      shell: "mysql -e \"SET PASSWORD = '{{ passwd_mysql_root }}';\"
         --connect-expired-password -uroot -p'{{ mysql_root_password_temp.stdout }}'
         && touch /root/.my.password.changed"
      args:
        creates: /root/.my.password.changed
      tags: never